apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: data-ingest-stock
  labels:
    app: data-ingest
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/your-repo/stock-pipeline"  # You'll need to commit to Git
      ref: main
    contextDir: "data-ingest"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "data-ingest:stock-v1.0"
  triggers:
  - type: ConfigChange
  - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: data-ingest
  labels:
    app: data-ingest
spec:
  lookupPolicy:
    local: false